### ISSUE TITLE
How to render Text from data?

### ISSUE THREAD

**Issue by wilkerlucio** [finnfiddle/number-picture#2]
Hello, I'm trying to figure how to print text from data, this is how I'm trying to do it:

```jsx
<Collection data={nodes}>
  <Text datum={p => p.datum.id}
        dx={p => p.index * 25 + 12.5}
        textAnchor="middle"/>
</Collection>
```

I saw in the docs I need to send the text as children, but how to get it from the datum?

**Comment by finnfiddle** [comment]
you're right I believe this isnt possible currently. Ill work something out in the next release. we can either have an extra prop on the Text component which overrides the children prop if defined or we can have optional Function as Child Component. Eg:
```
<Text>{(props) => props.datum.id}</Text>
```
Which do you think is better?

**Comment by finnfiddle** [comment]
or we can move away from having children at all and just use a specific custom prop for the text value, eg: ```<Text value="lorem" />```

**Comment by finnfiddle** [comment]
or all of the above :)

**Comment by wilkerlucio** [comment]
I like the `value` prop approach, most of the texts are just a print operation. The one on children sounds interesting, but at same I'm not sure how you would handle that, is it easy to parse functions inside of children?

**Comment by finnfiddle** [comment]
yeah I guess its more simple having a value prop

**Comment by finnfiddle** [comment]
@wilkerlucio the library has been completely rewritten (and renamed) and has a much simpler API now as a result of switching to a render props approach. It would be great to get feedback on it if you have any. The new docs can be found here: http://numberpicture.com/build
