### ISSUE TITLE
Examples? Force-directed graph

### ISSUE THREAD

**Issue by obiwan007** [finnfiddle/number-picture#8]
Do you have any more complex examples on how you would build a xy diagram?
u.E. with two independent y-axis.

I need to do a force directed-graph simulation with a few 1000 elements too. 
Based on the example from https://bl.ocks.org/mbostock/4062045 that would be difficult currently in react.

**Comment by finnfiddle** [comment]
regarding an XY diagram I dont have a ready example but here is an X diagram which you can look at to see the general principles of how you would do it: http://numberpicture.com/chart/s

Regarding a force directed graph - this is something that plain D3 would be a better option to use currently for performance reasons. Potion is an abstraction on top of both D3 and React so you lose some performance as a result and when you have large datasets this will become noticeable.
