### ISSUE TITLE
any plan to support brushChart?

### ISSUE THREAD

**Issue by wulucxy** [finnfiddle/number-picture#9]
@finnfiddle  I have one case of great mount of data to show,  it's not possible to show all the data in the chart, and may be brushChart is a solution。

so， do you have any plan to support the brush chart?

thanks for the great work done for visualization。

**Comment by finnfiddle** [comment]
Hi @wulucxy - unfortunately this seems like something that is beyond the scope of this library. Potion is a low-level as possible and does not provide high-level components like the one you're asking about. Similarly to D3, Potion is designed to be used as a base for more high-level software.

This would need to be made custom - and when you change the selection of the brush then you would filter the data yourself and pass it to the Potion Layout. Hope that makes sense
